sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket-name: my-web-fenghongtao
    region: cn-hangzhou
    #      oss:我的bucket示例
    #        endpoint: https://oss-cn-hangzhou.aliyuncs.com
    #        bucketName: my-web-fenghongtao
    #        region: cn-hangzhou
  redis:
    database: 0
    host: localhost
    port: 6379
  wechat:
    secret: 7a43d710d514ea6cd52a023253400438
    app-id: wx987a2d57e3c632d2